# https://docs.docker.com/compose/compose-file
version: '3.9'
services:
    db:
    #   build: ./mongo/.
    #   volumes:
    #     - lf-mongo-data:/data/db
      image: mongo:4.0
      restart: always
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
      # volumes:
        # - TODO: need to provide custom conf and get it in the right location=> ./mongod.conf:/data/db

    db-admin-ui: # localhost:81
      image: mongo-express
      ports:
          - 81:8081
      depends_on:
          - db
      restart: always
      environment:
          ME_CONFIG_MONGODB_SERVER: db
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: example

    php-test:
      build:
        context: ..
        dockerfile: docker/php-test/Dockerfile

    # php-api:
    #   build: php-api/.

    lfmerge:
      build: lfmerge/.
      volumes:
        - lf-lfmerge:/var/lib/languageforge

volumes:
#   lf-mongo-data:
  lf-lfmerge:
