# https://docs.docker.com/compose/compose-file
version: '3.9'
services:
    db:
      image: mongo:4.0
      volumes:
        - mongo-data:/data/db
      restart: always

    php-test:
      container_name: php-test
      # profiles: ["test"]
      build:
        context: ..
        dockerfile: docker/php-test/Dockerfile
      volumes:
        - ../test:/data/test
      # these paths are mapped in for developer convenience
        - ../src/index.php:/var/www/html/index.php
        - ../src/angular-app:/var/www/html/angular-app
        - ../src/Api:/var/www/html/Api
        - ../src/Site:/var/www/html/Site
      depends_on:
          - db
          - mail

    node:
      container_name: node
      build:
        context: ..
        dockerfile: docker/node/Dockerfile
      volumes:
        - ../src:/data/src
        - ../typings:/data/typings
        - ../webpack.config.js:/data/webpack.config.js
        - ../gulpfile.js:/data/gulpfile.js

    php-api:
      container_name: php-api
      image: lf-php-api
      build:
        context: ..
        dockerfile: docker/php-api/Dockerfile
      volumes:
        - user-data-assets:/var/www/html/assets
        # because the composer vendor dependencies are build inside the container but reside in /var/www/html,
        # we have to manually mount each src folder and file in.
        # TODO: make the application run without having the vendor and src folders tied together so closely
        # This could probably be accomplished with a fancy Apache rewrite script
        # ALTERNATIVE: many of these files could be COPYed in at build time, but then the image would need to be
        # rebuilt if these files were modified (many are unlikely to be modified regularly)
        - ../src/index.php:/var/www/html/index.php
        - ../src/angular-app:/var/www/html/angular-app
        - ../src/Api:/var/www/html/Api
        - ../src/Site:/var/www/html/Site
        - ../src/dist:/var/www/html/dist
        - ../src/appManifest:/var/www/html/appManifest
        - ../src/help:/var/www/html/help
        - ../src/js:/var/www/html/js
        - ../src/json:/var/www/html/json
        - ../src/releasenotes:/var/www/html/releasenotes
        - ../src/resources:/var/www/html/resources
        - ../src/.htaccess:/var/www/html/.htaccess
        - ../src/app_dependencies.json:/var/www/html/app_dependencies.json
        - ../src/config.php:/var/www/html/config.php
        - ../src/favicon.ico:/var/www/html/favicon.ico
        - ../src/offline.html:/var/www/html/offline.html
        - ../src/offlineCheck.txt:/var/www/html/offlineCheck.txt
        - ../src/site_wide_notices.json:/var/www/html/site_wide_notices.json
        - ../src/version.php:/var/www/html/version.php

      depends_on:
        - db
        - mail

    ssl:
        image: caddy
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
          - php-api
        # https://caddyserver.com/docs/command-line
        command: caddy reverse-proxy --from localhost --to php-api

    mail:
      container_name: mail
      environment:
        SMTP_SERVER: example.com
        SMTP_USERNAME: chris
        SMTP_PASSWORD: password
        SERVER_HOSTNAME: example.com
      build:
        context: mail

    lfmerge:
      container_name: lfmerge
      build: lfmerge/.
      volumes:
        - lfmerge-data:/var/lib/languageforge

    db-reset:
      image: lf-php-api
      depends_on:
        - db
        - mail
      working_dir: /var/www/scripts/tools
      volumes:
        - ../scripts/:/var/www/scripts
      command: php FactoryReset.php run

volumes:
  mongo-data:
  lfmerge-data:
  caddy_data:
  caddy_config:
  user-data-assets:
