# https://docs.docker.com/compose/compose-file
version: '3.9'
services:
    db:
      volumes:
        - mongo-data:/data/db
      image: mongo:4.0
      container_name: db
      restart: always
      # - TODO: need to provide custom conf and get it in the right location=> ./mongod.conf:/data/db

    db-admin-ui: # http://localhost:81
      image: mongo-express
      container_name: db-admin-ui
      ports:
          - 81:8081
      depends_on:
          - db
      restart: always
      environment:
          ME_CONFIG_MONGODB_SERVER: db

    php-test:
      container_name: php-test
      build:
        context: ..
        dockerfile: docker/php-test/Dockerfile
      volumes:
        - ../test:/data/test
      # these paths are mapped in for developer convenience
        - ../src/index.php:/var/www/html/index.php
        - ../src/angular-app:/var/www/html/angular-app
        - ../src/Api:/var/www/html/Api
        - ../src/Site:/var/www/html/Site
      depends_on:
          - db
          - mail

    node:
      container_name: node
      build:
        context: ..
        dockerfile: docker/node/Dockerfile
      volumes:
        - ../.:/data

    php-api:
      container_name: php-api
      image: php-api:latest
      build:
        context: ..
        dockerfile: docker/php-api/Dockerfile
      volumes:
      # these paths are mapped in for developer convenience
        - ../src/index.php:/var/www/html/index.php
        - ../src/angular-app:/var/www/html/angular-app
        - ../src/Api:/var/www/html/Api
        - ../src/Site:/var/www/html/Site
      depends_on:
          - db
          - mail

    ssl:
        image: caddy
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
          - php-api
        # https://caddyserver.com/docs/command-line
        command: caddy reverse-proxy --from localhost --to php-api

    mail:
      container_name: mail
      environment:
        SMTP_SERVER: example.com
        SMTP_USERNAME: chris
        SMTP_PASSWORD: password
        SERVER_HOSTNAME: example.com
      build:
        context: mail

    lfmerge:
      container_name: lfmerge
      build: lfmerge/.
      volumes:
        - lfmerge-data:/var/lib/languageforge

volumes:
  mongo-data:
  lfmerge-data:
  dist-data:
  caddy_data:
  caddy_config:
