# https://docs.docker.com/compose/compose-file
version: '3.9'
services:
    db:
      volumes:
        - lf-mongo-data:/data/db
      image: mongo:4.0
      container_name: db
      restart: always
      # - TODO: need to provide custom conf and get it in the right location=> ./mongod.conf:/data/db

    db-admin-ui: # http://localhost:81
      image: mongo-express
      ports:
          - 81:8081
      depends_on:
          - db
      restart: always
      environment:
          ME_CONFIG_MONGODB_SERVER: db
          #ME_CONFIG_MONGODB_ADMINUSERNAME: root
          #ME_CONFIG_MONGODB_ADMINPASSWORD: example

    php-test:
      container_name: php-test
      build:
        context: ..
        dockerfile: docker/php-test/Dockerfile
      volumes:
        - ../.:/data
      depends_on:
          - db
          - mail

    node:
      container_name: node
      build:
        context: ..
        dockerfile: docker/node/Dockerfile
      volumes:
        - ../.:/data

    # php-api:
    #   build: php-api/.

    mail:
      container_name: mail
      environment:
        SMTP_SERVER: example.com
        SMTP_USERNAME: chris
        SMTP_PASSWORD: password
        SERVER_HOSTNAME: example.com
      build:
        context: mail

    lfmerge:
      container_name: lfmerge
      build: lfmerge/.
      volumes:
        - lf-lfmerge:/var/lib/languageforge

volumes:
  lf-mongo-data:
  lf-lfmerge:
